#!/bin/bash
echo "============================================"
echo "  localchimera Provider Status Dashboard"
echo "============================================"
echo ""
echo "--- Running Processes ---"
ps aux | grep -E "salad-worker|byteleap-worker|nosana|provider-services|k3s|python.*miner" | grep -v grep | grep -v "status.sh"
echo ""
echo "--- k3s Cluster ---"
sudo kubectl --kubeconfig /etc/rancher/k3s/k3s.yaml get nodes 2>/dev/null || echo "k3s: kubectl not accessible"
echo ""
echo "--- Docker ---"
sudo docker ps 2>/dev/null | head -5 || echo "Docker: no containers"
echo ""
echo "--- Wallets ---"
ls -la ~/.nosana/nosana_key.json 2>/dev/null && echo "Nosana: ~/.nosana/nosana_key.json exists"
echo ""
echo "============================================"
