name = "new-localchimera"
compatibility_date = "2024-12-01"

# Cloudflare Pages configuration
pages_build_output_dir = "dist"

# Cloudflare KV namespace for domain registrar orders and contacts.
[[kv_namespaces]]
binding = "DOMAIN_KV"
id = "682d080c6e514539b724e3702e9786fa"
