import { BookOpen, Tag, FileText, FolderTree } from 'lucide-react';

const WIKI_PAGES = [
  { id: 'index.md', active: true, icon: '📄' },
  { id: 'log.md', active: false, icon: '📄' },
  { id: 'concepts/index.md', active: false, icon: '📄' },
  { id: 'concepts/getting-started.md', active: false, icon: '📝' },
  { id: 'concepts/ai-writing-guide.md', active: false, icon: '📝' },
  { id: 'concepts/p2p-sync.md', active: false, icon: '📝' },
  { id: 'concepts/mining-setup.md', active: false, icon: '📝' },
  { id: 'reference/index.md', active: false, icon: '📑' },
  { id: 'reference/markdown-syntax.md', active: false, icon: '📝' },
];

export default function ConsoleWiki() {
  return (
    <div className="max-w-[1200px] grid grid-cols-1 lg:grid-cols-4 gap-4">
      <div className="bg-white border border-[#e5e5e5] rounded-[14px] p-4 lg:col-span-1">
        <div className="flex items-center gap-2 mb-3">
          <FolderTree className="w-4 h-4 text-[#6b7280]" />
          <div className="text-[12px] font-semibold text-[#6b7280] uppercase tracking-wide">Wiki</div>
        </div>
        <div className="space-y-1">
          <div className="text-[10px] font-semibold text-[#9ca3af] uppercase tracking-wide py-1">OKF Bundle</div>
          {WIKI_PAGES.slice(0, 2).map((p) => (
            <button key={p.id} className={`w-full text-left flex items-center gap-2 px-2.5 py-1.5 rounded-[8px] text-[13px] ${p.active ? 'bg-[#f5f5f7] text-[#111111] font-semibold' : 'text-[#6b7280] hover:bg-[#f5f5f7]'}`}>
              <span>{p.icon}</span> {p.id}
            </button>
          ))}
          <div className="text-[10px] font-semibold text-[#9ca3af] uppercase tracking-wide py-1">concepts/</div>
          {WIKI_PAGES.slice(2, 7).map((p) => (
            <button key={p.id} className={`w-full text-left flex items-center gap-2 px-2.5 py-1.5 rounded-[8px] text-[13px] ${p.active ? 'bg-[#f5f5f7] text-[#111111] font-semibold' : 'text-[#6b7280] hover:bg-[#f5f5f7]'}`}>
              <span>{p.icon}</span> {p.id.replace('concepts/', '')}
            </button>
          ))}
          <div className="text-[10px] font-semibold text-[#9ca3af] uppercase tracking-wide py-1">reference/</div>
          {WIKI_PAGES.slice(7).map((p) => (
            <button key={p.id} className={`w-full text-left flex items-center gap-2 px-2.5 py-1.5 rounded-[8px] text-[13px] ${p.active ? 'bg-[#f5f5f7] text-[#111111] font-semibold' : 'text-[#6b7280] hover:bg-[#f5f5f7]'}`}>
              <span>{p.icon}</span> {p.id.replace('reference/', '')}
            </button>
          ))}
        </div>
      </div>

      <div className="bg-white border border-[#e5e5e5] rounded-[14px] p-6 lg:col-span-3">
        <div className="text-[12px] font-mono text-[#6b7280] mb-6 border border-[#e5e5e5] rounded-[10px] p-3 bg-[#f5f5f7]">
          <div className="font-semibold text-[#6b7280] mb-2">Frontmatter (OKF)</div>
          <div>id: <span className="text-[#9333ea] font-medium">index</span></div>
          <div>title: <span className="text-[#0284c7] font-medium">Welcome to Chimera</span></div>
          <div>tags: <span className="text-emerald-600 font-medium">wiki, ai, okf</span></div>
        </div>

        <h1 className="text-[26px] font-bold text-[#111111] mb-3">Welcome to Chimera</h1>
        <p className="text-[14px] text-[#6b7280] mb-6">This is your personal wiki powered by local AI inference.</p>

        <h2 className="text-[18px] font-bold text-[#111111] border-b border-[#e5e5e5] pb-2 mb-4">Getting Started</h2>
        <ul className="list-disc list-inside text-[14px] text-[#6b7280] mb-6 space-y-1">
          <li>Use the <strong className="text-[#111111]">AI Writer</strong> panel to generate content</li>
          <li>Edit markdown directly in the editor</li>
          <li>Preview renders your markdown in real-time</li>
        </ul>

        <h2 className="text-[18px] font-bold text-[#111111] border-b border-[#e5e5e5] pb-2 mb-4">Example</h2>
        <pre className="bg-[#f5f5f7] border border-[#e5e5e5] rounded-[10px] p-4 text-[13px] font-mono text-[#111111] mb-6 overflow-x-auto">
{`// Generated by AI
console.log("Hello, wiki!");`}
        </pre>
        <blockquote className="border-l-4 border-[#c9a96e] pl-4 italic text-[#6b7280] mb-6">
          "Knowledge is power."
        </blockquote>

        <h2 className="text-[18px] font-bold text-[#111111] border-b border-[#e5e5e5] pb-2 mb-4">Related</h2>
        <ul className="list-disc list-inside text-[14px] text-[#6b7280] mb-6 space-y-1">
          <li><a className="text-[#0284c7] hover:underline" href="#">concepts/getting-started</a></li>
          <li><a className="text-[#0284c7] hover:underline" href="#">concepts/ai-writing-guide</a></li>
          <li><a className="text-[#0284c7] hover:underline" href="#" target="_blank" rel="noopener">Google Cloud Knowledge Catalog</a></li>
        </ul>

        <h2 className="text-[18px] font-bold text-[#111111] border-b border-[#e5e5e5] pb-2 mb-4">Bundle Structure</h2>
        <p className="text-[14px] text-[#6b7280] mb-4">This wiki follows the <a className="text-[#0284c7] hover:underline" href="#" target="_blank" rel="noopener">Open Knowledge Format</a>.</p>
        <pre className="bg-[#f5f5f7] border border-[#e5e5e5] rounded-[10px] p-4 text-[13px] font-mono text-[#111111] mb-6 overflow-x-auto">
{`chimera-wiki/
├── index.md                 # Root directory listing
├── log.md                   # Update history
├── concepts/
│   ├── index.md             # Concepts directory listing
│   ├── getting-started.md
│   ├── ai-writing-guide.md
│   ├── p2p-sync.md
│   └── mining-setup.md
└── reference/
    ├── index.md             # Reference directory listing
    └── markdown-syntax.md`}
        </pre>
        <div className="flex flex-wrap gap-2">
          <span className="inline-flex items-center gap-1 text-[12px] px-2.5 py-1 rounded-full border border-[#e5e5e5] text-[#6b7280]"><Tag className="w-3 h-3" />#wiki</span>
          <span className="inline-flex items-center gap-1 text-[12px] px-2.5 py-1 rounded-full border border-[#e5e5e5] text-[#6b7280]"><Tag className="w-3 h-3" />#ai</span>
          <span className="inline-flex items-center gap-1 text-[12px] px-2.5 py-1 rounded-full border border-[#e5e5e5] text-[#6b7280]"><Tag className="w-3 h-3" />#okf</span>
        </div>
      </div>
    </div>
  );
}
