export default {};
export const createTransactionMessage = () => {};
export const setTransactionMessageFeePayerSigner = () => {};
export const setTransactionMessageLifetimeUsingBlockhash = () => {};
export const getMinimumBalanceForRentExemption = () => 0;
export const getBase58Encoder = () => {};
export const address = () => {};
export const getAddressFromPublicKey = () => {};
export const getU8Encoder = () => {};
export const getProgramDerivedAddress = () => {};
export const addSignersToTransactionMessage = () => {};
export const getSignatureFromTransaction = () => {};
export const sendAndConfirmTransactionFactory = () => () => {};
export const generateKeyPairSigner = () => {};
export const createSolanaRpc = () => {};
export const pipe = () => {};
export const isAddress = () => false;
export const isSignature = () => false;
export const isKeyPairSigner = () => false;
